export {default as HomePage} from "./home"
export {default as SignInPage} from "./signin"
export {default as SignUpPage} from "./signup"
export {default as ResetPage} from "./reset"
export {default as CoursesPage} from "./courses"
export {default as CourseLab} from "./courseLab"